Repository DisasterKok/Disasterkok_backend, pull requests merged in 2023-11, with the labels that each got.

#12 Feature: google 소셜 로그인 구현 , setting : csrf 무시 설정
  webapp/config/authentications.py
  webapp/config/settings/base.py
  webapp/requirements.txt
  webapp/user/migrations/0002_user_googleid.py
  webapp/user/migrations/0003_alter_user_username.py
  webapp/user/models/user.py
  webapp/user/urls.py
  webapp/user/views/__init__.py
  webapp/user/views/googleLoginUserView.py
Labels: Feature, Setting

#11 Social login
  webapp/user/migrations/0002_user_googleid.py
  webapp/user/models/user.py
  webapp/user/urls.py
  webapp/user/views/__init__.py
  webapp/user/views/googleLoginUserView.py
Labels: Temp

#13 Feature: notification
  webapp/config/settings/base.py
  webapp/notification/__init__.py
  webapp/notification/admin/__init__.py
  webapp/notification/admin/notificationAdmin.py
  webapp/notification/apps.py
  webapp/notification/migrations/__init__.py
  webapp/notification/models/__init__.py
  webapp/notification/models/notification.py
  webapp/notification/serializers/__init__.py
  webapp/notification/tests.py
  webapp/notification/urls.py
  webapp/notification/views/__init__.py
  webapp/user/serializers/nicknameSerializer.py
  webapp/user/views/nicknameduplicateAPIView.py
Labels: Feature
